import "../styles/globals.css";
import { Header } from "@/components/layout/Header";
import { ProProvider } from "@/context/pro-context";
import { Footer } from "@/components/layout/Footer";

export const metadata = {
  title: "PAP",
  description: "Generated by create next app",
  icon: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Syne:wght@400..800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full bg-background flex flex-col">
        <ProProvider>
          <Header />
          <main className="min-h-screen">{children}</main>
        </ProProvider>
        <Footer />
      </body>
    </html>
  );
}
