import "../styles/globals.css";
import { Inter, Syne } from "next/font/google";
import { AppProvider } from "@/context/AppContext";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { ProProvider } from "@/context/pro-context";
import { verifySession } from "@/lib/dal";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  display: "swap",
});

export const metadata = {
  title: "PAP",
  description: "Generated by create next app",
  icon: "/favicon.ico",
};

export default async function RootLayout({ children }) {
  const session = await verifySession();

  return (
    <html
      lang="en"
      className={`${inter.variable} ${syne.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-background flex flex-col">
        <ProProvider
          initialIsPro={session?.isPro ?? false}
          initialName={session?.name ?? null}
          initialPricelistId={session?.pricelistId ?? null}
          initialIsConnected={!!session}
        >
          <AppProvider>
            <Header />
            <main className="min-h-screen">{children}</main>
          </AppProvider>
        </ProProvider>
        <Footer />
      </body>
    </html>
  );
}
